### PR TITLE
Added footer

### PR DESCRIPTION
**Pull request by AbhineshJha**
Added Footer in the base page of website >>

image

### CODE REVIEW

**Comment by Pavel401** [comment]
Please remove all this information and just add 'Made with love by developers.'

**Comment by AbhineshJha** [comment]
sure sir @Pavel401

**Comment by Pavel401** [comment]
@all-contributors
please add @AbhineshJha  for code

**Comment by Pavel401** [comment]
@all-contributors
please add @AbhineshJha  for code

**Comment by Pavel401** [comment]
@AbhineshJha, please star the repo ⭐️.

**Comment by AbhineshJha** [comment]
done @Pavel401

**Pull request merged**
